<a href="https://colab.research.google.com/github/ademaratioluwatoyin/Numpy/blob/main/PlayAroundNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
hamoye_2 = np.array([[1, 3, 5, 7],[2, 4, 6, 8]])
hamoye_2

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [5]:
hamoye_2[-1:, -2:]

array([[6, 8]])

In [6]:
hamoye_2.shape

(2, 4)

In [7]:
hamoye_2[-2:, -3:]

array([[3, 5, 7],
       [4, 6, 8]])

In [8]:
len(hamoye_2)

2

In [11]:
hamoye_2.ndim

2

# introduction

In [12]:
23 in hamoye_2

False

In [13]:
8 in hamoye_2

True

In [14]:
hamoye_range = np.array(range(20), float)
hamoye_range

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [19]:
hamoye_range = hamoye_range.reshape((4,5))
hamoye_range

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [20]:
hamoye_range.shape

(4, 5)

In [21]:
a = np.array([1, 2, 3, 4], float)
a.tolist()

[1.0, 2.0, 3.0, 4.0]

In [22]:
list(a)

[1.0, 2.0, 3.0, 4.0]

In [23]:
a.fill(1)

In [24]:
a

array([1., 1., 1., 1.])

In [25]:
my_list = [1, 2 , 3, 4, 5, 6]

In [27]:
my_array = np.array(my_list, float).reshape(2,3)
my_array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
my_list1 = ['bread', 'beans', 'egg']
my_array1 = np.array(my_list1)

In [29]:
my_array1

array(['bread', 'beans', 'egg'], dtype='<U5')

In [30]:
hamoye_range.transpose()

array([[ 0.,  5., 10., 15.],
       [ 1.,  6., 11., 16.],
       [ 2.,  7., 12., 17.],
       [ 3.,  8., 13., 18.],
       [ 4.,  9., 14., 19.]])

In [31]:
hamoye_2.flatten()

array([1, 3, 5, 7, 2, 4, 6, 8])

In [35]:
a = np.array([3,5,7], float)
b = np.array([1,11], float)
c = np.array([5,8,9], float)
np.concatenate((a,b,c))

array([ 3.,  5.,  7.,  1., 11.,  5.,  8.,  9.])

In [39]:
np.arange(20, dtype = int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
np.arange(1,20,3, dtype = float)

array([ 1.,  4.,  7., 10., 13., 16., 19.])

In [43]:
np.eye(5, k = -2, dtype = float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [45]:
a = np.array([[1,3], [0,5], [2, -1]])
b = np.array([1,11])
a * b

array([[  1,  33],
       [  0,  55],
       [  2, -11]])

In [49]:
z = np.array([6.27, 2.6, 5.4, 1.192])
np.floor(z)

array([6., 2., 5., 1.])

In [47]:
np.ceil(z)

array([7., 3., 6., 2.])

In [50]:
np.rint(z)

array([6., 3., 5., 1.])